### ISSUE TITLE
max_allowed_packet did not propagate to the databse

### ISSUE THREAD

**Issue by kjgarza** [datacite/sashimi#40]
https://stackoverflow.com/questions/5688403/how-to-check-and-set-max-allowed-packet-mysql-variable.

ActiveRecord::StatementInvalid: Mysql2::Error: Access denied; you need (at least one of) the SUPER privilege(s) for this operation: set global max_allowed_packet=64000000;
/home/app/webapp/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/home/app/webapp/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/home/app/webapp/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/

**Comment by kjgarza** [comment]
I talked with DataOne, they will be able to send smaller report by node. However they need to find a way to define the difference between report creator  and publisher.

Next actions 
- [ ] disscuss how to change creator
- [ ] remove change in sashimi about max allowed package
